updates to dockerfile to run kaldb and dependencies locally
slackhq/astra pull request #779
Opened 2024-02-22 22:24 UTC by autata

###  Summary
This PR updates the dockerfile to:

1. renames dependencies `dep_` to make it easier to differentiate the containers when printed alphabetically.
2. makes one service per kaldb node type with necessary flags changes so kaldb nodes can communicate with each other.

The flows I've tested with this PR are ingestion via bulk ingest and read via _msearch on the query node. So the following flow:
```
/_bulk -> preprocessor -> internal kafka topic -> indexer -> query node _msearch
```
S3, recovery nodes, and cache nodes were not confirmed to work yet.

More work is needed to fully test and setup locally. But here are the current instructions that work for this PR:

#### 1. in terminal, build and run compose to bring up dependencies and kaldb nodes
```
docker build -t slackhq/kaldb .

docker compose up
```

#### 2. in kafka container terminal, create input topic (preprocessor crashes if it does not exist before configuring manager in next step) 
```
kafka-topics.sh --create --topic test-topic-in --bootstrap-server localhost:9092
```

#### 3. run 2 curl commands to configure 1 partition
```
curl -XPOST -H 'content-type: application/json; charset=utf-8; protocol=gRPC' http://localhost:8083'/slack.proto.kaldb.ManagerApiService/CreateDatasetMetadata' -d '{
  "name": "test",
  "owner": "test@email.com",
  "serviceNamePattern": "_all"
}'

curl -XPOST -H 'content-type: application/json; charset=utf-8; protocol=gRPC' http://localhost:8083'/slack.proto.kaldb.ManagerApiService/UpdatePartitionAssignment' -d '{
  "name": "test",
  "throughputBytes": "1000000",
  "partitionIds": ["0"]
}'
```

#### 4. Add some logs via bulk ingest
Note: `timestamp` is required
```
curl --location 'http://localhost:8086/_bulk' \
--header 'Content-type: application/x-ndjson' \
--data '{ "index" : { "_index" : "test", "_id" : "100" } }
{ "timestamp": "2024-02-16T14:30:00-06:00[America/Chicago]", "level": "INFO", "message": "This is a log message", "service-name": "test" }
'
```

#### 5. Example curl to read data
Note: This is similar to [ES _msearch](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-multi-search.html) but `size`, `lte`, and `gte` are all required or else a 500 error occurs. In follow-up work, I will clean up those endpoints to return a 400 (bad request) with detail about the missing required argument.
```
curl --location 'http://localhost:8081/_msearch' \
--header 'Content-type: application/x-ndjson' \
--data '{ "index": "test"}
{"query" : {"match_all" : {}, "gte":1625156649889,"lte":2708540790265}, "size": 500}
'
```

### Requirements

* [x] I've read and understood the [Contributing Guidelines](CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2024-02-22 23:28 UTC, autata commented
@bryanlb do you have an example payload of what `test-topic-in` is expecting? I'm able to run and test kaldb using bulk ingest, but haven't gotten it working by adding logs/traces to the input topic.

2024-02-27 18:03 UTC, bryanlb commented
@autata the `upstreamTopics` and `downstreamTopic` were to support a Kafka streaming approach for an internal format that was used by Slack, and is not officially supported. These code paths will be removed in favor of exclusively using the `_bulk` ingest once we have finished switching our internal use completely to bulk ingest.

You should be able to point Logstash to the KalDB cluster with bulk ingest, as long as you address the few endpoints that Logstash needs for discovery (primarily `/` and `/_license`). These aren't part of KalDB, but can be provided to Logstash with something like an Envoy `direct_response_route`.

2024-03-13 21:12 UTC, bryanlb requested changes
Hey @autata! I made a few suggestions with some naming changes, and then I believe this needs to be updated against master as it's showing it's out-of-date. I like the prefixing of `dep`, and splitting up this into multiple services is a great idea!

2024-03-18 16:25 UTC, autata commented on docker-compose.yml
> +    image: 'slackhq/kaldb'
renamed!

2024-03-18 16:28 UTC, autata commented
@bryanlb changed the names

I'm not sure why the fork is behind slackhq/astra as I've "refreshed" it. But either way, there are no conflicts so i think this would be ok to merge as is.

I can always re-open a new PR using a different fork (https://github.com/autata/kaldb/tree/master doesn't seem to have this issue)

2024-03-18 16:56 UTC, bryanlb approved these changes

2024-03-18 16:56 UTC, bryanlb commented
This is great, thanks so much @autata!

2024-03-18 16:56 UTC, merged

2024-03-18 17:06 UTC, vthacker commented
Should we copy the workflow that @autata has mentioned in the description and move it to a getting started guide? This could be a subpage and linked from the README?

2024-03-18 17:09 UTC, bryanlb commented
@vthacker I think that this is probably something we'll want to add to the docs site?

What I'm currently thinking is that we'll keep the README in the main repo, and then pretty much everything else will go to the docs site (including the current wiki content). That seems to be a clear way to maintain our docs moving forward, and kinda prevent the current situation where they're spread around a lot of different places.

2024-03-18 17:10 UTC, autata commented
@vthacker @bryanlb I copied the instructions into a discussion here: https://github.com/slackhq/astra/discussions/799

so it lives past this PR. there were some open items I think could make it more seamless, outlined in the discussion. But I agree, moving to onboarding makes sense