index an additional @timestamp field
slackhq/astra pull request #909
Opened 2024-05-01 00:04 UTC by vthacker

###  Summary

2024-05-01 18:03 UTC, vthacker commented on astra/src/main/java/com/slack/astra/metadata/schema/FieldType.java
> +        LONG.addField(doc, name, value, fieldDef);
so when we deploy the indexer first, docs will keep getting added as this. Once we deploy preprocessor the object will become LocalDateTime

2024-05-01 20:06 UTC, bryanlb requested changes
Consider also adding a test for a timestamp that comes in with a timezone other than UTC, and ensure it's converted correctly. Just to make sure this doesn't regress.

2024-05-01 20:06 UTC, bryanlb commented on astra/src/main/java/com/slack/astra/bulkIngestApi/opensearch/BulkApiRequestParser.java
> +      // As I understand frontend UIs expect this to be constant at UTC and they adjust it based on
Instant can always be considered UTC (ie, https://www.baeldung.com/java-instant-vs-localdatetime#:~:text=The%20easiest%20way%20to%20think,in%20the%20UTC%20time%20zone). You can see this also in the javadocs for `Instant.atOffset()`.

As such we'd always want to store this at UTC, and you are correct that timezone conversions are done at query time - https://github.com/slackhq/astra/blob/master/astra/src/main/java/com/slack/astra/logstore/opensearch/OpenSearchAdapter.java#L985

2024-05-01 22:34 UTC, vthacker commented
> Consider also adding a test for a timestamp that comes in with a timezone other than UTC, and ensure it's converted correctly. Just to make sure this doesn't regress.

I believe that this will break today. We use the ISO_INSTANT formatter which only accepts time in UTC. I believe a good way to improve this in the future is to paraterize this and let the user pass their data format.

2024-05-01 23:32 UTC, vthacker commented on astra/src/main/java/com/slack/astra/bulkIngestApi/opensearch/BulkApiRequestParser.java
> -      if (ingestDocument.hasField("@timestamp")) {
hasField basically gets sourceAndMetadata so the change shouldn't have any effect.

2024-05-01 23:50 UTC, bryanlb submitted a review, later dismissed

2024-05-02 16:07 UTC, bryanlb submitted a review, later dismissed

2024-05-02 18:09 UTC, merged